linters-settings:
  varnamelen:
    min-name-length: 1
linters:
  enable-all: true
  disable:
    - bodyclose
    - exhaustivestruct
    - exhaustruct
    - godox
    - ireturn
    # disable because deprecated
    - golint
    - interfacer
    - maligned
    - scopelint
    # disable because go 1.18
    - contextcheck
    - interfacer
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - wastedassign
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - path: main.go
      linters:
        - funlen
    - path: http.go
      linters:
        - funlen
run:
  skip-dirs:
    - design
    - cmd
    - gen
