linters-settings:
  varnamelen:
    min-name-length: 1
linters:
  enable-all: true
  disable:
    - bodyclose
    - exhaustivestruct
    - exhaustruct
    - godox
    - ireturn
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - path: main.go
      linters:
        - funlen
    - path: http.go
      linters:
        - funlen
run:
  skip-dirs:
    - design
    - cmd
    - gen
