name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Goa install
        run: go install goa.design/goa/v3/cmd/goa@latest
      - name: Goa generate
        run: goa gen github.com/morning-night-dream/play-cicd/design
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
