name: release

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Goa install
        run: go install goa.design/goa/v3/cmd/goa@latest
      - name: Set version
        run: |
          version=v`date +%Y%m%d%H%M%S`
          echo "VERSION=${version}" >> $GITHUB_ENV
      - name: Docker Login
        run: echo "${{ secrets.GIT_DOCKER_PAT }}" | docker login ghcr.io -u ${OWNER,,} --password-stdin
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
